from uuid import UUID

from django.http import JsonResponse
from django.utils import timezone

from apps.accounts.models import Profile
from apps.videos.models import Video, VideoComment, VideoLike
from apps.store import get_identity, parse_json_request, response_envelope


def _method_not_allowed(*allowed_methods: str) -> JsonResponse:
    return JsonResponse({'detail': 'Method not allowed.', 'allowed': list(allowed_methods)}, status=405)


def upload_url_view(request):
    # POST /api/videos/upload-url/ - create a presigned upload target for a new video.
    if request.method != 'POST':
        return _method_not_allowed('POST')

    payload = parse_json_request(request)
    identity = get_identity(request, payload)
    
    # Ensure profile exists
    Profile.objects.update_or_create(
        clerk_user_id=identity['clerk_user_id'],
        defaults={
            'email': identity['email'],
            'username': identity['username'],
            'display_name': identity['display_name'],
            'avatar_url': identity['avatar_url'],
        }
    )
    
    # Create video record (upload_url would normally be generated by storage service)
    video = Video.objects.create(
        owner_clerk_user_id=identity['clerk_user_id'],
        title=str(payload.get('title') or 'Untitled dashcam clip').strip(),
        description=str(payload.get('description') or '').strip(),
        visibility=str(payload.get('visibility') or 'public').strip() or 'public',
        status='pending',
        original_filename=str(payload.get('original_filename') or payload.get('filename') or ''),
        tags=[str(tag).strip() for tag in payload.get('tags', []) if str(tag).strip()] if isinstance(payload.get('tags', []), list) else [],
    )

    return JsonResponse(
        response_envelope(
            'video-upload-url',
            {
                'video': video.to_dict(),
                'upload': {
                    'method': 'PUT',
                    'url': video.upload_url,
                    'headers': {'Content-Type': payload.get('content_type', 'video/mp4')},
                },
            },
        ),
        status=200,
    )
    
def complete_upload_view(request):
    # POST /api/videos/complete/ - mark an upload complete and enqueue processing.
    if request.method != 'POST':
        return _method_not_allowed('POST')

    payload = parse_json_request(request)
    video_id_raw = payload.get('video_id')
    if not video_id_raw:
        return JsonResponse({'detail': 'video_id is required.'}, status=400)

    try:
        video_id = UUID(str(video_id_raw))
    except ValueError:
        return JsonResponse({'detail': 'video_id must be a valid UUID.'}, status=400)

    # Lookup video
    try:
        video_uuid = UUID(str(video_id_raw))
    except ValueError:
        return JsonResponse({'detail': 'video_id must be a valid UUID.'}, status=400)

    try:
        video = Video.objects.get(id=video_uuid)
    except Video.DoesNotExist:
        return JsonResponse({'detail': 'Video not found.'}, status=404)

    video.status = 'processing'
    video.save(update_fields=['status', 'updated_at'])
    return JsonResponse(
        response_envelope(
            'video-complete',
            {
                'video': video.to_dict(),
                'message': 'Upload marked complete. Processing would be queued here.',
            },
        ),
        status=200,
    )


def video_detail_view(request, video_id):
    # GET /api/videos/<video_id>/ - return the full video object and metadata.
    if request.method != 'GET':
        return _method_not_allowed('GET')

    try:
        video_uuid = UUID(str(video_id))
    except ValueError:
        return JsonResponse({'detail': 'Invalid video_id format.'}, status=400)

    try:
        video = Video.objects.get(id=video_uuid)
    except Video.DoesNotExist:
        return JsonResponse({'detail': 'Video not found.'}, status=404)

    if video.deleted_at is not None:
        return JsonResponse({'detail': 'Video not found.'}, status=404)

    # Increment view count
    video.views += 1
    video.save(update_fields=['views', 'updated_at'])

    return JsonResponse(response_envelope('video', {'video': video.to_dict()}), status=200)


def video_status_view(request, video_id):
    # GET /api/videos/<video_id>/status/ - return processing/upload status.
    if request.method != 'GET':
        return _method_not_allowed('GET')
    try:
        video_uuid = UUID(str(video_id))
    except ValueError:
        return JsonResponse({'detail': 'Invalid video_id format.'}, status=400)

    try:
        video = Video.objects.get(id=video_uuid)
    except Video.DoesNotExist:
        return JsonResponse({'detail': 'Video not found.'}, status=404)

    if video.deleted_at is not None:
        return JsonResponse({'detail': 'Video not found.'}, status=404)

    return JsonResponse(response_envelope('video-status', {'video': {'id': str(video.id), 'status': video.status}}), status=200)


def video_update_delete_view(request, video_id):
    # PATCH / DELETE for video metadata or soft-delete
    if request.method not in ('PATCH', 'DELETE'):
        return _method_not_allowed('PATCH', 'DELETE')

    try:
        video_uuid = UUID(str(video_id))
    except ValueError:
        return JsonResponse({'detail': 'Invalid video_id format.'}, status=400)

    try:
        video = Video.objects.get(id=video_uuid)
    except Video.DoesNotExist:
        return JsonResponse({'detail': 'Video not found.'}, status=404)

    if video.deleted_at is not None:
        return JsonResponse({'detail': 'Video not found.'}, status=404)

    if request.method == 'PATCH':
        payload = parse_json_request(request)
        updated_fields = []

        if 'title' in payload:
            video.title = str(payload.get('title', video.title)).strip() or video.title
            updated_fields.append('title')
        if 'description' in payload:
            video.description = str(payload.get('description', video.description)).strip()
            updated_fields.append('description')
        if 'visibility' in payload:
            video.visibility = str(payload.get('visibility', video.visibility)).strip() or video.visibility
            updated_fields.append('visibility')
        if 'tags' in payload and isinstance(payload.get('tags'), list):
            video.tags = [str(tag).strip() for tag in payload.get('tags', []) if str(tag).strip()]
            updated_fields.append('tags')

        if updated_fields:
            updated_fields.append('updated_at')
            video.save(update_fields=updated_fields)

        return JsonResponse(response_envelope('video', {'video': video.to_dict()}), status=200)

    # DELETE - soft delete
    video.deleted_at = timezone.now()
    video.status = 'deleted'
    video.save(update_fields=['deleted_at', 'status', 'updated_at'])
    return JsonResponse({'detail': 'Video deleted.', 'video_id': str(video.id)}, status=200)
