# Generated by Django 5.2.14 on 2026-05-20 04:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_clerk_user_id', models.CharField(db_index=True, help_text='Clerk user ID of the video owner', max_length=255)),
                ('title', models.CharField(default='Untitled dashcam clip', help_text='Video title', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Video description')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', help_text='Video visibility setting', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', help_text='Processing status (pending, processing, ready, failed)', max_length=20)),
                ('original_filename', models.CharField(blank=True, default='', help_text='Original filename from upload', max_length=255)),
                ('upload_url', models.URLField(blank=True, default='', help_text='Presigned upload URL (temporary)')),
                ('playback_url', models.URLField(blank=True, default='', help_text='CDN/playback URL for the video')),
                ('thumbnail_url', models.URLField(blank=True, default='', help_text='Thumbnail image URL')),
                ('duration_seconds', models.IntegerField(default=0, help_text='Video duration in seconds')),
                ('views', models.IntegerField(default=0, help_text='Number of views')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tag strings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_clerk_user_id', '-created_at'], name='videos_vide_owner_c_72f4ad_idx'), models.Index(fields=['status'], name='videos_vide_status_107761_idx'), models.Index(fields=['visibility'], name='videos_vide_visibil_7be839_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_clerk_user_id', models.CharField(db_index=True, help_text='Clerk user ID of the commenter', max_length=255)),
                ('text', models.TextField(help_text='Comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(help_text='The video being commented on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['video', '-created_at'], name='videos_vide_video_i_947613_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_clerk_user_id', models.CharField(db_index=True, help_text='Clerk user ID of the liker', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(help_text='The video being liked', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('video', 'user_clerk_user_id')},
            },
        ),
    ]
