# Generated by Django 5.2.14 on 2026-05-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_comment_replies_and_likes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='videocomment',
            new_name='videos_vide_parent__cd026e_idx',
            old_name='videos_video_parent_c3e4c2_idx',
        ),
    ]
