# Generated by Django - normalize legacy tag strings into source-aware objects.
from django.db import migrations


def normalize_tags(apps, schema_editor):
    Video = apps.get_model('videos', 'Video')
    for video in Video.objects.all().only('id', 'tags'):
        tags = video.tags or []
        normalized = []
        seen = set()
        if isinstance(tags, list):
            for tag in tags:
                if isinstance(tag, dict):
                    text = str(tag.get('text') or tag.get('name') or tag.get('label') or '').strip()
                    source = str(tag.get('source') or 'user').strip().lower()
                else:
                    text = str(tag or '').strip()
                    source = 'user'

                if not text:
                    continue
                if source not in {'user', 'admin', 'ai'}:
                    source = 'user'
                key = text.lower()
                if key in seen:
                    continue
                seen.add(key)
                normalized.append({'text': text, 'source': source})

        if normalized != tags:
            video.tags = normalized
            video.save(update_fields=['tags'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_rename_videos_video_parent_c3e4c2_idx_videos_vide_parent__cd026e_idx'),
    ]

    operations = [
        migrations.RunPython(normalize_tags, noop_reverse),
    ]
