# Generated by Django 5.2.14 on 2026-06-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_normalize_video_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.CharField(help_text='Unique worker identifier (e.g., caden-desktop-1)', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable worker name', max_length=255)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA256 hash of the API token', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this worker is active')),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('idle', 'Idle'), ('processing', 'Processing'), ('error', 'Error')], default='offline', help_text='Current worker status', max_length=20)),
                ('current_job', models.UUIDField(blank=True, help_text='Currently processing video ID', null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last heartbeat timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='ai_events',
            field=models.JSONField(blank=True, default=list, help_text='AI-detected events in the video with timestamps'),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional AI analysis metadata'),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated summary of video content'),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated tags for the video'),
        ),
        migrations.AddField(
            model_name='video',
            name='analysis_completed_at',
            field=models.DateTimeField(blank=True, help_text='When analysis completed', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='analysis_error',
            field=models.TextField(blank=True, default='', help_text='Error message if analysis failed'),
        ),
        migrations.AddField(
            model_name='video',
            name='analysis_failed_at',
            field=models.DateTimeField(blank=True, help_text='When analysis failed', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='analysis_progress',
            field=models.IntegerField(default=0, help_text='Analysis progress 0-100'),
        ),
        migrations.AddField(
            model_name='video',
            name='analysis_requested_at',
            field=models.DateTimeField(blank=True, help_text='When analysis was requested', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='analysis_stage',
            field=models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('downloading', 'Downloading'), ('analyzing', 'Analyzing'), ('uploading_results', 'Uploading Results'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', help_text='Detailed stage within analysis workflow', max_length=25),
        ),
        migrations.AddField(
            model_name='video',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, help_text='When analysis started (worker claimed job)', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='AI analysis status (pending, processing, complete, failed, cancelled)', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='worker_claimed_at',
            field=models.DateTimeField(blank=True, help_text='When the worker claimed this job', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='worker_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID of the worker processing this job', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='worker_last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Last heartbeat from the worker', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='worker_name',
            field=models.CharField(blank=True, default='', help_text='Name of the worker processing this job', max_length=255),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['analysis_status'], name='videos_vide_analysi_e74274_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['worker_id'], name='videos_vide_worker__fe0d70_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-worker_last_seen_at'], name='videos_vide_worker__1e57e8_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['is_active'], name='videos_work_is_acti_0148d4_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['-last_seen_at'], name='videos_work_last_se_fd640a_idx'),
        ),
    ]
