# Generated by Django 5.2.17 on 2026-08-07 23:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_worker_video_ai_events_video_ai_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='approval_decided_at',
            field=models.DateTimeField(blank=True, help_text='When the approval decision was made', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='approval_decided_by',
            field=models.CharField(blank=True, default='', help_text='Clerk user ID of whoever approved or rejected', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='approval_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending_review', help_text='Whether this video has been approved for analysis', max_length=20),
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(help_text='1 for the first request, incrementing per re-analysis')),
                ('status', models.CharField(choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='awaiting_approval', max_length=20)),
                ('requested_by', models.CharField(blank=True, default='', help_text='Clerk user ID that requested this analysis, blank if automatic', max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.CharField(blank=True, default='', help_text='Clerk user ID that approved or rejected this attempt', max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, default='', max_length=255)),
                ('worker_name', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('events', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('video', models.ForeignKey(help_text='The video this attempt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='videos.video')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['video', '-requested_at'], name='videos_anal_video_i_82283d_idx'), models.Index(fields=['status'], name='videos_anal_status_5cf923_idx')],
                'constraints': [models.UniqueConstraint(fields=('video', 'attempt_number'), name='unique_attempt_number_per_video')],
            },
        ),
    ]
