# Generated by Django 5.2.17 on 2026-08-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_backfill_approval_and_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='analysis_priority',
            field=models.IntegerField(db_index=True, default=0, help_text='Higher runs sooner. Ties fall back to when analysis was requested.'),
        ),
    ]
