# Generated by Django 5.2.17 on 2026-08-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video_analysis_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='analysis_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending Analysis'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='AI analysis status (pending, processing, complete, failed, cancelled)', max_length=20),
        ),
    ]
