# Generated by Django 5.2.14 on 2026-09-28 02:03

import apps.incidents.crypto
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0010_backfill_not_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('contact_sheet', 'Contact sheet'), ('frame', 'Frame'), ('burst', 'Burst frame'), ('vehicle_crop', 'Vehicle crop'), ('plate_crop', 'Plate crop'), ('text_crop', 'Text crop'), ('photo', 'Supplementary photo')], max_length=20)),
                ('storage_path', models.CharField(max_length=512)),
                ('content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('sha256', models.CharField(max_length=64)),
                ('t_seconds', models.FloatField(blank=True, help_text='Position in the video, if any', null=True)),
                ('bbox', models.JSONField(blank=True, help_text='[x, y, w, h] in source pixels, if a crop', null=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('analyzer_version', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_artifacts', to='videos.video')),
            ],
            options={
                'ordering': ['t_seconds', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(help_text='SHA-256 of the bytes received at upload', max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField()),
                ('history', models.JSONField(blank=True, default=list)),
                ('worker_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('worker_id', models.CharField(blank=True, default='', max_length=255)),
                ('worker_checked_at', models.DateTimeField(blank=True, null=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_record', to='videos.video')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', apps.incidents.crypto.EncryptedTextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incident_report', to='videos.video')),
            ],
        ),
        migrations.CreateModel(
            name='OtherParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', apps.incidents.crypto.EncryptedTextField(blank=True, default='')),
                ('phone', apps.incidents.crypto.EncryptedTextField(blank=True, default='')),
                ('email', apps.incidents.crypto.EncryptedTextField(blank=True, default='')),
                ('address', apps.incidents.crypto.EncryptedTextField(blank=True, default='')),
                ('drivers_license', apps.incidents.crypto.EncryptedTextField(blank=True, default='')),
                ('vehicle_plate', apps.incidents.crypto.EncryptedTextField(blank=True, default='')),
                ('vehicle_description', apps.incidents.crypto.EncryptedTextField(blank=True, default='')),
                ('insurer', apps.incidents.crypto.EncryptedTextField(blank=True, default='')),
                ('policy_number', apps.incidents.crypto.EncryptedTextField(blank=True, default='')),
                ('claim_number', apps.incidents.crypto.EncryptedTextField(blank=True, default='')),
                ('police_report_number', apps.incidents.crypto.EncryptedTextField(blank=True, default='')),
                ('notes', apps.incidents.crypto.EncryptedTextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_party', to='incidents.incidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('update', 'Updated')], max_length=10)),
                ('as_admin', models.BooleanField(default=False)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_access_log', to='videos.video')),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['video', '-at'], name='incidents_i_video_i_c1327f_idx')],
            },
        ),
    ]
