# Generated by Django 5.2.14 on 2026-09-28 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('videos', '0010_backfill_not_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceartifact',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_artifacts', to='videos.analysisrun'),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='provenance_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencerecord',
            name='sha256',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of the bytes received at upload', max_length=64),
        ),
        migrations.AlterField(
            model_name='evidencerecord',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
