# Generated by Django 5.2.14 on 2026-09-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_evidenceartifact_run_evidencerecord_provenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerecord',
            name='moments',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='moments_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
