# Generated by Django 5.2.14 on 2026-09-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_evidencerecord_moments_evidencerecord_moments_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerecord',
            name='overlay',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='overlay_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
