# Generated by Django 5.2.14 on 2026-09-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_evidencerecord_overlay_evidencerecord_overlay_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceartifact',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evidenceartifact',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='evidenceartifact',
            name='preview_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
