# Generated by Django 5.2.14 on 2026-09-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_evidenceartifact_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentaccesslog',
            name='action',
            field=models.CharField(choices=[('view', 'Viewed'), ('update', 'Updated'), ('export', 'Exported')], max_length=10),
        ),
    ]
