# Generated by Django 5.2.14 on 2026-09-28 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_alter_incidentaccesslog_action'),
        ('videos', '0010_backfill_not_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_seconds', models.FloatField()),
                ('analyzer_version', models.CharField(blank=True, default='', max_length=50)),
                ('verdict', models.CharField(choices=[('incident', 'This is the incident'), ('not_incident', 'Not an incident')], max_length=20)),
                ('listed_as', models.CharField(default='moment', max_length=10)),
                ('score', models.FloatField(blank=True, null=True)),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('labelled_by', models.CharField(max_length=255)),
                ('labelled_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_labels', to='videos.video')),
            ],
            options={
                'ordering': ['video', 't_seconds'],
                'constraints': [models.UniqueConstraint(fields=('video', 't_seconds', 'analyzer_version'), name='one_label_per_moment')],
            },
        ),
    ]
