# Generated by Django 5.2.14 on 2026-05-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.CharField(db_index=True, help_text='Unique identifier from Clerk auth', max_length=255, unique=True)),
                ('email', models.EmailField(help_text='User email address', max_length=254)),
                ('username', models.CharField(db_index=True, help_text='Unique handle for profile URLs', max_length=255, unique=True)),
                ('display_name', models.CharField(help_text='Display name visible to other users', max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='', help_text='Profile picture URL from Clerk or custom source')),
                ('bio', models.TextField(blank=True, default='', help_text='User bio or description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clerk_user_id'], name='accounts_pr_clerk_u_d9bf31_idx'), models.Index(fields=['username'], name='accounts_pr_usernam_a5e02d_idx')],
            },
        ),
    ]
